version: "3"
services:
  binpoll-back:
    image: pantoniuk/binpoll-back
    build: 
      context: webapp-back
      args:
        BINPOLL_DB_NAME: binpoll
        BINPOLL_DB_USER: binpoll
        BINPOLL_DB_PASS: binpoll
        BINPOLL_DB_PORT: 3306
        BINPOLL_DB_HOST: database
    command: ["./wait-for-it.sh", "database:3306", "-t", "30", "--", "bash", "/app/configure.sh"]
    tty: true
    container_name: binpoll-back
    ports:
      - "8000:80"
    networks:
      - webnet
#    volumes:
#      -  ./webapp-back/binpoll-back:/app/binpoll-back
  binpoll-front:
    image: pantoniuk/binpoll-front
    build: 
      context: webapp-front
      args:
        BINPOLL_API_URL:  http://localhost:8000/
    tty: true
    container_name: binpoll-front
    ports:
      - "80:80"
  database:
    image: pantoniuk/binpoll-db
    build: database
    container_name: binpoll-db
    environment:
      - MYSQL_ROOT_PASSWORD=binpoll
      - MYSQL_DATABASE=binpoll
      - MYSQL_USER=binpoll
      - MYSQL_PASSWORD=binpoll
    ports:
      - "3306:3306"
    networks:
      - webnet
#    volumes:
#      -  ./webapp-front/binpoll-front:/app/binpoll-front
networks:
  webnet:
volumes:
  binpoll-back-src:
  binpoll-front-src: